parameters:
    tables.avathar.postlove: '%core.table_prefix%posts_likes'
services:
    avathar.postlove.listener:
        class: avathar\postlove\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '%tables.avathar.postlove%'
        tags:
            - {name: event.listener}
    avathar.postlove.summary_listener:
        class: avathar\postlove\event\summary_listener
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@dispatcher'
            - '@template'
            - '@user'
            - '@language'
            - '@avathar.postlove.forum_access'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
        tags:
            - {name: event.listener}
    avathar.postlove.ajaxify:
        class: avathar\postlove\controller\ajaxify
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@language'
            - '@cache'
            - '@request'
            - '@avathar.postlove.notifyhelper'
            - '%tables.avathar.postlove%'
    avathar.postlove.lovelist:
        class: avathar\postlove\controller\lovelist
        arguments:
            - '@user'
            - '@language'
            - '@controller.helper'
            - '@dbal.conn'
            - '@auth'
            - '@content.visibility'
            - '@user_loader'
            - '@template'
            - '@pagination'
            - '@request'
            - '@avathar.postlove.forum_access'
            - '%tables.avathar.postlove%'
            - '%core.root_path%'
            - '%core.php_ext%'
    avathar.postlove.notifyhelper:
        class: avathar\postlove\controller\notifyhelper
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%tables.avathar.postlove%'
    avathar.postlove.topic_likes:
        class: avathar\postlove\service\topic_likes
        arguments:
            - '@dbal.conn'
            - '%tables.avathar.postlove%'
    avathar.postlove.forum_access:
        class: avathar\postlove\service\forum_access
        arguments:
            - '@dbal.conn'
            - '@user'
    avathar.postlove.notification.type.postlove:
        class: avathar\postlove\notification\postlove
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
        tags:
            - {name: notification.type}

