name: Tests

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'develop-*'
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
    with:
      EXTNAME: 'anavaro/postlove'
